import keyMirror from 'keymirror';

export default keyMirror({
  RECEIVE_CHALLONGE_TOURNAMENT: null,
  RECEIVE_CHALLONGE_TOURNAMENTS: null,
  RECEIVE_CHALLONGE_TOURNAMENT_ERROR: null,
  RECEIVE_CHALLONGE_TOURNAMENTS_ERROR: null,
  RECEIVE_CHALLONGE_TOURNAMENT_PARTICIPANTS: null,
  RECEIVE_CHALLONGE_TOURNAMENT_PARTICIPANTS_ERROR: null,
  RECEIVE_CHALLONGE_TOURNAMENT_MATCHES: null,
  RECEIVE_CHALLONGE_TOURNAMENT_MATCHES_ERROR: null
});